#!/usr/bin/env Rscript
for (f in list.files('R',full.names=TRUE,pattern='\\.R$')) source(f)
expect_error <- function(expr,pattern) {
  e <- tryCatch({ force(expr); NULL },error=identity)
  stopifnot(inherits(e,'error'),grepl(pattern,conditionMessage(e)))
}
tmp <- tempfile('cytof-tests-'); dir.create(tmp)
for (d in c('intensities','regionprops')) dir.create(file.path(tmp,d))
write_csv(data.frame(channel=c('a','b','c'),name=c('CD3','CD20','constant'),use_channel=c(TRUE,TRUE,FALSE)),file.path(tmp,'panel.csv'))
write_csv(data.frame(image=c('roi_A.tiff','roi_B.tiff'),width_px=20,height_px=20),file.path(tmp,'images.csv'))
write_csv(data.frame(roi_id=c('roi_B','roi_A'),sample_name=c('B','A')),file.path(tmp,'mapping.csv'))
set.seed(1)
for (roi in c('roi_A','roi_B')) {
  write_csv(data.frame(Object=1:30,a=rgamma(30,2),b=rgamma(30,5),c=1),file.path(tmp,'intensities',paste0(roi,'.csv')))
  write_csv(data.frame(Object=30:1,area=c(rep(10,29),1)),file.path(tmp,'regionprops',paste0(roi,'.csv')))
}
cfg <- parse_args(c('--input',tmp,'--samples',file.path(tmp,'mapping.csv'),'--output',file.path(tmp,'out'),'--skip-images','--skip-embeddings'))
d <- read_input(cfg)
stopifnot(dim(d$counts)==c(3,60),d$cells$sample_name[1]=='A',d$cells$area[1]==1,identical(colnames(d$counts),d$cells$cell_id))
# Quoted and unquoted CSV headers can preserve whitespace differently.
panel_path <- file.path(tmp,'panel.csv')
original_panel <- read_table(panel_path)
spaced_panel <- original_panel; spaced_panel$name <- c(' CD3 ', 'CD20 ', 'constant')
write_csv(spaced_panel,panel_path)
for (roi in c('roi_A','roi_B')) {
  path <- file.path(tmp,'intensities',paste0(roi,'.csv'))
  intensity <- read_table(path); names(intensity)[-1] <- c('CD3', ' CD20 ', 'constant')
  write_csv(intensity,path)
}
stopifnot(identical(read_input(cfg)$counts,d$counts))
bad_panel <- spaced_panel; bad_panel$name[2] <- 'CD3'
write_csv(bad_panel,panel_path)
expect_error(read_input(cfg),'unique')
write_csv(original_panel,panel_path)
path <- file.path(tmp,'intensities','roi_A.csv')
intensity <- read_table(path); duplicate <- intensity
names(duplicate)[3] <- ' CD3 '
write_csv(duplicate,path)
expect_error(read_input(cfg),'unique')
write_csv(intensity,path)
y <- transform_counts(d$counts,'arcsinh_zscore',cfg)
stopifnot(max(abs(rowMeans(y)))<1e-12,all(y[3,]==0),abs(sd(y[1,])-1)<1e-12)
expect_error(validate_rlog(d$counts,1000),'integer counts')
expect_error(validate_rlog(matrix(1,3,1001),1000),'exceeds')
expect_error(parse_args(c('--input','x','--samples','y','--output','z','--cofactor','0')),'positive')
expect_error(parse_args(c('--unknown')),'Unknown')
metrics <- roi_metrics(d,cfg)
stopifnot(all(metrics$cells_after==29),all(metrics$coverage==291/400),all(metrics$cells_per_mm2==29/(400/1e6)))
write_matrix(d$counts,file.path(tmp,'matrix.csv.gz'),chunk=7)
back <- read.csv(gzfile(file.path(tmp,'matrix.csv.gz')),check.names=FALSE)
stopifnot(identical(back$cell_id,d$cells$cell_id),isTRUE(all.equal(as.matrix(back[,-1]),t(d$counts),check.attributes=FALSE)))
stopifnot(is.infinite(snr_partition(c(0,0,2,2),c(FALSE,FALSE,TRUE,TRUE))['snr']))
stopifnot(all(is.na(snr_partition(1:3,rep(TRUE,3)))))
review <- marker_review(data.frame(marker=c('high','weak','zero'),signal=c(20,1,20),snr=c(20,30,Inf)),cfg)
stopifnot(grepl('High SNR',review$review[1]),grepl('low positive',review$review[2]),grepl('zero background',review$review[3]))
dir.create(file.path(tmp,'report')); dir.create(file.path(tmp,'report','plots'))
r <- new_report(file.path(tmp,'report'))
report_text(r,'Test <script>','Escaped & reproducible')
report_plot(r,'Heatmap','Test explanation',function() graphics::plot(1:10,y[1,1:10]))
report_plot(r,'One value','Single marker/ROI',function() graphics::plot(1,1))
finish_report(r)
stopifnot(file.info(file.path(tmp,'report','report.pdf'))$size>1000,any(grepl('&lt;script&gt;',readLines(file.path(tmp,'report','report.html')),fixed=TRUE)))
write_csv(data.frame(roi_id='roi_A',sample_name='A'),cfg$samples)
expect_error(read_input(cfg),'Unmapped')
write_csv(data.frame(roi_id=c('roi_A','roi_B'),sample_name=c('A','B')),cfg$samples)
plot_deps <- c('dittoSeq','patchwork','ggrastr','viridis','RColorBrewer','SingleCellExperiment')
have_plots <- all(vapply(plot_deps,requireNamespace,logical(1),quietly=TRUE))
if (have_plots) {
  # Four input-ordered patients: the old first-N rendering omitted later groups.
  meta <- d$cells; meta$patient_id <- rep(paste0('patient_',1:4),each=15)
  meta <- plot_metadata(meta)
  obj <- expression_object(y,meta)
  SingleCellExperiment::reducedDim(obj,'UMAP') <- cbind(seq_len(ncol(obj)),seq_len(ncol(obj)))
  SingleCellExperiment::reducedDim(obj,'TSNE') <- cbind(seq_len(ncol(obj)),seq_len(ncol(obj)))
  colors <- plot_colors(meta)
  p <- embedding_metadata_grid(obj,colors,'patient_id')
  built <- ggplot2::ggplot_build(p[[1]])
  stopifnot(nrow(built$data[[1]])==60,length(unique(built$data[[1]]$colour))==4)
  panel <- embedding_marker_grid(obj,'UMAP')
  stopifnot(nrow(ggplot2::ggplot_build(panel[[1]])$data[[1]])==60)
  stopifnot(inherits(panel[[1]]$scales$get_scales('colour'),'ScaleContinuous'))
  cat('PASS: all four patients and all embedded cells retained, continuous marker color scale\n')
}
if (have_plots && requireNamespace('mclust',quietly=TRUE)) {
  run_qc(cfg)
  stopifnot(readLines(file.path(cfg$output,'STATUS'))=='complete')
  expect_error(run_qc(cfg),'must be empty')
  cat('PASS: complete pipeline with image/embedding opt-outs\n')
} else cat('SKIP: pipeline integration requires mclust\n')
if (have_plots && all(vapply(c('mclust','uwot','Rtsne','scater'),requireNamespace,logical(1),quietly=TRUE))) {
  cfg$output <- file.path(tmp,'with_embeddings'); cfg$skip_embeddings <- FALSE
  run_qc(cfg)
  e <- read.csv(file.path(cfg$output,'coordinates','arcsinh_UMAP.csv'))
  stopifnot(nrow(e)==58,all(is.finite(e$UMAP1)))
  cat('PASS: embedding integration\n')
} else cat('SKIP: embedding integration requires mclust, uwot, Rtsne\n')
if (have_plots && all(vapply(c('mclust','EBImage','tiff','cytomapper'),requireNamespace,logical(1),quietly=TRUE))) {
  dir.create(file.path(tmp,'img')); dir.create(file.path(tmp,'masks'))
  for (roi in c('roi_A','roi_B')) {
    pages <- lapply(1:3,function(j) matrix(runif(400),20,20))
    tiff::writeTIFF(pages,file.path(tmp,'img',paste0(roi,'.tiff')),bits.per.sample=32)
    mask <- matrix(0,20,20); mask[1:30] <- 1:30
    tiff::writeTIFF(mask/65535,file.path(tmp,'masks',paste0(roi,'.tiff')),bits.per.sample=16)
    stopifnot(setequal(unique(as.vector(read_raw_tiff(file.path(tmp,'masks',paste0(roi,'.tiff'))))),0:30))
  }
  cfg$output <- file.path(tmp,'with_images'); cfg$skip_images <- FALSE; cfg$skip_embeddings <- TRUE
  run_qc(cfg)
  pixel <- read.csv(file.path(cfg$output,'tables','pixel_snr.csv'))
  stopifnot(nrow(pixel)==6,all(is.finite(pixel$signal)))
  cat('PASS: raw TIFF labels, image SNR and overlay integration\n')
} else cat('SKIP: image integration requires mclust, EBImage, tiff\n')
if (requireNamespace('DESeq2',quietly=TRUE)) {
  set.seed(42)
  counts <- matrix(rnbinom(400,size=2,mu=20),40,10,dimnames=list(paste0('M',1:40),paste0('C',1:10)))
  a <- transform_counts(counts,'rlog',cfg)
  z <- transform_counts(counts,'rlog_zscore',cfg)
  stopifnot(identical(dim(a),dim(counts)),all(is.finite(a)),max(abs(rowMeans(z)))<1e-10)
  cat('PASS: genuine DESeq2 rlog and rlog z-score\n')
} else cat('SKIP: rlog integration requires DESeq2\n')
unlink(tmp,recursive=TRUE)
cat('PASS: base-R validation, joins, transforms, QC metrics, exports and HTML/PDF tests\n')
